//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CustomSearchBar.Resources.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LanguageResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LanguageResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CustomSearchBar.Resources.Languages.LanguageResources", typeof(LanguageResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add To Basket.
        /// </summary>
        internal static string MainPage_btn_AddToBasket {
            get {
                return ResourceManager.GetString("MainPage_btn_AddToBasket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name 1.
        /// </summary>
        internal static string MainPage_Classification1 {
            get {
                return ResourceManager.GetString("MainPage_Classification1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name 2.
        /// </summary>
        internal static string MainPage_Classification2 {
            get {
                return ResourceManager.GetString("MainPage_Classification2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name 3.
        /// </summary>
        internal static string MainPage_Classification3 {
            get {
                return ResourceManager.GetString("MainPage_Classification3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name 4.
        /// </summary>
        internal static string MainPage_Classification4 {
            get {
                return ResourceManager.GetString("MainPage_Classification4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string MainPage_ety_SearchPlaceHolder {
            get {
                return ResourceManager.GetString("MainPage_ety_SearchPlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu 1.
        /// </summary>
        internal static string MainPage_FoodMenu1 {
            get {
                return ResourceManager.GetString("MainPage_FoodMenu1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu 2.
        /// </summary>
        internal static string MainPage_FoodMenu2 {
            get {
                return ResourceManager.GetString("MainPage_FoodMenu2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu 3.
        /// </summary>
        internal static string MainPage_FoodMenu3 {
            get {
                return ResourceManager.GetString("MainPage_FoodMenu3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu 4.
        /// </summary>
        internal static string MainPage_FoodMenu4 {
            get {
                return ResourceManager.GetString("MainPage_FoodMenu4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu 5.
        /// </summary>
        internal static string MainPage_FoodMenu5 {
            get {
                return ResourceManager.GetString("MainPage_FoodMenu5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu 6.
        /// </summary>
        internal static string MainPage_FoodMenu6 {
            get {
                return ResourceManager.GetString("MainPage_FoodMenu6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عربي.
        /// </summary>
        internal static string MainPage_lbl_Language {
            get {
                return ResourceManager.GetString("MainPage_lbl_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mixed Grill.
        /// </summary>
        internal static string MainPage_lbl_Meal {
            get {
                return ResourceManager.GetString("MainPage_lbl_Meal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thimar.
        /// </summary>
        internal static string MainPage_NameApp {
            get {
                return ResourceManager.GetString("MainPage_NameApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mohamed Fawzy.
        /// </summary>
        internal static string SideMenu_Heaer_PersonName {
            get {
                return ResourceManager.GetString("SideMenu_Heaer_PersonName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Profile.
        /// </summary>
        internal static string SideMenu_ItemTitle_01 {
            get {
                return ResourceManager.GetString("SideMenu_ItemTitle_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Cart.
        /// </summary>
        internal static string SideMenu_ItemTitle_02 {
            get {
                return ResourceManager.GetString("SideMenu_ItemTitle_02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My wishlist.
        /// </summary>
        internal static string SideMenu_ItemTitle_03 {
            get {
                return ResourceManager.GetString("SideMenu_ItemTitle_03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment.
        /// </summary>
        internal static string SideMenu_ItemTitle_04 {
            get {
                return ResourceManager.GetString("SideMenu_ItemTitle_04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notifcations.
        /// </summary>
        internal static string SideMenu_ItemTitle_05 {
            get {
                return ResourceManager.GetString("SideMenu_ItemTitle_05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categories.
        /// </summary>
        internal static string SideMenu_ItemTitle_06 {
            get {
                return ResourceManager.GetString("SideMenu_ItemTitle_06", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Orders.
        /// </summary>
        internal static string SideMenu_ItemTitle_07 {
            get {
                return ResourceManager.GetString("SideMenu_ItemTitle_07", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string SideMenu_ItemTitle_08 {
            get {
                return ResourceManager.GetString("SideMenu_ItemTitle_08", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Live Chat.
        /// </summary>
        internal static string SideMenu_ItemTitle_09 {
            get {
                return ResourceManager.GetString("SideMenu_ItemTitle_09", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        internal static string SideMenu_ItemTitle_10 {
            get {
                return ResourceManager.GetString("SideMenu_ItemTitle_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string SideMenu_ItemTitle_11 {
            get {
                return ResourceManager.GetString("SideMenu_ItemTitle_11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        internal static string SideMenu_ItemTitle_12 {
            get {
                return ResourceManager.GetString("SideMenu_ItemTitle_12", resourceCulture);
            }
        }
    }
}
